name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' # نسخة 11 هي اللي تمشي مع فلاتر القديم

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5' # هادي هي النسخة السحرية لحل مشكلتك
          channel: 'stable'

      - name: Repair Project
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        # هاد الأمر يتجاهل كل مشاكل الـ Null Safety والـ Embedding
        run: flutter build apk --release --no-sound-null-safety
