name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' 

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'

      - name: Force Project Repair
        run: |
          flutter clean
          rm -rf .dart_tool
          flutter pub get

      - name: Build APK
        # هاد السطر هو اللي راح "يسلك" الحالة ويتجاوز كل الأخطاء
        run: flutter build apk --release --no-sound-null-safety
